### ISSUE TITLE
BUG: The !list command intermittently fails to respond

### ISSUE THREAD

**Issue by jegillikin** [aigeroni/Winnie_Bot#124] opened 2020-11-15 21:55 UTC
**DESCRIPTION**: The `!list` command intermittently fails to respond.

**SYNTAX USED**:  `!list`

**EXPECTED BEHAVIOR**: A list of currently active challenges.

**SCREENSHOTS**:  N/A

**ADDITIONAL CONTEXT**: No other Winnie commands seem affected. Only `!list`, and only intermittently. For example, it failed to respond at 15:03 (-5 GMT) on 15 Nov 2020, from several users in several channels. Then at 15:20 it responded again, but by 16:25 (through at least 16:45) the command returned no response.

_Also, I didn't do it this time._

**Comment by lisushka** [comment] 2020-11-15 22:28
Duplicate of #106.  This is because the user base has outscaled the way that the `!list` command was set up, and so it's hitting Discord's 2000-character limit for messages during peak hours.

**Closed by lisushka** 2020-11-15 22:28 UTC
